apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: user-service
  name: user-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: user-service
  template:
    metadata:
      labels:
        run: user-service
    spec:
      containers:
      - name: user-service
        image: umesh0110/user-service:V7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80